version: "2.3"

services:
  jupyter_keras_2_2_4_cpu:
    build: jupyter_keras_2_2_4_cpu
    volumes:
      - ./:/shared
    ports:
      - 8888:8888
    working_dir: /shared/notebook
    command: jupyter notebook --ip=0.0.0.0 --allow-root --NotebookApp.token=''
  jupyter_pytorch_1_0_0_gpu:
    build: jupyter_pytorch_1_0_0_gpu
    runtime: nvidia
    environment:
      - VIDIA_DRIVER_CAPABILITIES=compute,utility
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - 28888:8888
    volumes:
      - ./:/shared
    command: bash -c "cd /shared/notebook && jupyter notebook --ip=0.0.0.0 --allow-root --NotebookApp.token=''"
  train_keras_2_2_4_cpu:
    build: train_keras_2_2_4_cpu
    volumes:
      - ./:/shared
    working_dir: /shared/train_keras_2_2_4_cpu
    command: python train.py
  train_keras_2_2_4_gpu:
    build: train_keras_2_2_4_gpu
    runtime: nvidia
    environment:
      - VIDIA_DRIVER_CAPABILITIES=compute,utility
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./:/shared
    working_dir: /shared/train_keras_2_2_4_cpu
    command: python train.py
